# Generated by Django 4.0.4 on 2022-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='domain',
            field=models.TextField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problems',
            name='complexity',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='problems',
            name='desc',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='problems',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
